### ISSUE TITLE
Locations of the NPC

### ISSUE THREAD

**Issue by cptcl** [ZhengPeiRu21/mod-reagent-bank#11]
Sorry if this sounds dumb, but where can i find this NPC?

**Comment by FutterSillo** [comment]
Hey, I hope I can help you out. I faced the same problem. Apparently, the NPC is not placed automatically but needs to be manually placed by a GM.

- Find a desired position for the NPC, meaning you need to walk to the point in the world with your in-game character (which must be GM level 3) where you want to place it.

- Align your character in the direction where the NPC should be looking by default.

- Enter the following into the chat window: `.npc add 290011`


For me, the ID was 290011, but it might be different for you. You need to check in the MySQL database: "acore_world" > "creature_template", sorting by the largest entry. Make sure the "name" field includes "Ling".
That's a rough summary; I hope it helps you.

**Comment by cptcl** [comment]
Thank u very much. This helps. Thats what i thought. and i figured out 90% of this by myself.
But your explaination will help every other ppl who has the same problem.
