### ISSUE TITLE
conf/conf.sh.dist missing/wrong folder structure

### ISSUE THREAD

**Issue by It0w** [ZhengPeiRu21/mod-reagent-bank#5]
Dear Sir,

thank you for this great Modul. Love it so far.

You might by notice that the folder you are pointing in ```conf/conf.sh.dist``` are incorrect and need to be adjusted or the folder them self need to be edited to reflect the "standard" folder stucture.

Thanks Itow

**Comment by ZhengPeiRu21** [comment]
Thank you for point out this issue! I have updated the paths in https://github.com/ZhengPeiRu21/mod-reagent-bank/commit/818916bb1c3232b63c6a0c3ca222faef49a90033. Please let me know if you continue to see any problem.
