### ISSUE TITLE
Wrong scaling on gossip window?

### ISSUE THREAD

**Issue by Ormusn2o** [ZhengPeiRu21/mod-reagent-bank#7]
![image](https://user-images.githubusercontent.com/22747011/224723637-ea9f2fcb-60b3-4852-a3c3-9d4e57e7b5db.png)

The reagent window has bigger icons than shown in the main page examples. This results in need for scrolling to pick up items lower down. I'm running "AzerothCore Individual Progression Single Player Repack" so its not from github so i assume this is the problem. I can include any files just i need to know which one. I disabled all addons and this is still the result.

**Comment by ZhengPeiRu21** [comment]
This may be due to your UI scaling settings. Please check the values in the WTF/Config.wtf file in your client. The values I used in the screenshot are:
```
SET uiScale "0.63999998569489"
SET useUiScale "1"
```

**Comment by Ormusn2o** [comment]
That solved it, thanks!
