### ISSUE TITLE
No gossip titles

### ISSUE THREAD

**Issue by Addri** [ZhengPeiRu21/mod-reagent-bank#9]
![image](https://github.com/ZhengPeiRu21/mod-reagent-bank/assets/18415398/8be138bd-e867-4083-b010-b16522158296)

Installed as normal, applied the SQLs to the correct place and I can use the banker, it stores my items and I can see them in the DB, but there is no gossip other than ? and the icons

**Comment by nilskus** [comment]
Same issue here... not sure if these issues are still being looked at but would be super nice to have a solution for this :)

![image](https://github.com/ZhengPeiRu21/mod-reagent-bank/assets/118109588/b633e854-0315-4b98-ac9b-0150be3180b0)

**Comment by ZhengPeiRu21** [comment]
This may have been caused by a recent update changing gossip signatures. I will look into it. Thanks for reporting the issue!

**Comment by ZhengPeiRu21** [comment]
I'm not able to replicate this issue using the latest version of this module and the current AzerothCore master. Are you using any other modules or client edits?
